version: '3.3'

services:
  node:
    build:
      args:
        NODE_ENV: develop
        NODE_VERSION: --lts
      context: .
      dockerfile: Dockerfile
    environment:
      - NEVATRAVEL=${NEVATRAVEL}
      - ASTRAMARIN_USERNAME=${ASTRAMARIN_USERNAME}
      - ASTRAMARIN_PASSWORD=${ASTRAMARIN_PASSWORD}
      - ASTRAMARIN=${ASTRAMARIN}
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - .docker/nginx/conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # - dhparam:/etc/ssl/certs
    depends_on:
      - node
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email info@nevatrip.ru --agree-tos --no-eff-email --force-renewal -d api.nevatrip.ru

  mongo:
    build: ./.docker/mongo
    ports:
      - '27017:27017'
    volumes:
      - ./.docker/data/mongo/:/var/lib/mongodb

  redis:
    build:
      context: ./.docker/redis
    ports:
      - '6379:6379'
    volumes:
      - ./.docker/data/redis:/data
    sysctls:
      - net.core.somaxconn=511


volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/deploy/api/public/
      o: bind
  # dhparam:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/deploy/api/dhparam/
  #     o: bind

networks:
  app-network:
    driver: bridge
