version: '3.3'

services:
  node:
    build:
      context: ./node
      args:
        - NODE_VERSION=latest
        - PROJECT_PATH=/opt/app/
        - NODE_ENV=develop
        - YARN=false
    volumes:
      - ../:/opt/app
    environment:
      - SERVER_URL=${SERVER_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - NEVATRAVEL=${NEVATRAVEL}
      - ASTRAMARIN_USERNAME=${ASTRAMARIN_USERNAME}
      - ASTRAMARIN_PASSWORD=${ASTRAMARIN_PASSWORD}
      - CLOUDPAYMENTS_PRIVATEKEY=${CLOUDPAYMENTS_PRIVATEKEY}
      - CLOUDPAYMENTS_PUBLICID=${CLOUDPAYMENTS_PUBLICID}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - ATOL_LOGIN=${ATOL_LOGIN}
      - ATOL_TOKEN=${ATOL_TOKEN}
      - ATOL_GROUP=${ATOL_GROUP}
      - SECRET=${SECRET}
    entrypoint: run-nodock "npm start"
    tty: true
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
    networks:
      - app-network

  redis:
    build:
      context: ./redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    sysctls:
      - net.core.somaxconn=511
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx/conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - node
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    # command: certonly --webroot --webroot-path=/var/www/html --email tech-support@nevatrip.ru --agree-tos --no-eff-email --staging -d api.nevatrip.ru
    command: certonly --webroot --webroot-path=/var/www/html --email tech-support@nevatrip.ru --agree-tos --no-eff-email --force-renewal -d api.nevatrip.ru

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/deploy/api/public/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/deploy/api/.docker/nginx/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
