version: '3.3'

services:
  node:
    entrypoint: run-nodock "npm start"
    environment:
      - NEVATRAVEL=${NEVATRAVEL}
      - ASTRAMARIN_USERNAME=${ASTRAMARIN_USERNAME}
      - ASTRAMARIN_PASSWORD=${ASTRAMARIN_PASSWORD}
      - ASTRAMARIN=${ASTRAMARIN}
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      args:
        - WEB_SSL=true
    volumes:
      - ./data/logs/nginx/:/var/log/nginx
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    # 1 command: certonly --webroot --webroot-path=/var/www/html --email info@api.nevatrip.ru --agree-tos --no-eff-email --staging -d api.nevatrip.ru
    command: certonly --webroot --webroot-path=/var/www/html --email info@api.nevatrip.ru --agree-tos --no-eff-email --force-renewal -d api.nevatrip.ru

  redis:
    networks:
      - app-network

  mongo:
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/deploy/api/public/
      o: bind

networks:
  app-network:
    driver: bridge
